### Samples ##
# The samplesheet.csv need to be in the same directory as this config file.
# The first column of the samplesheet contains the sample names. The second and third columns contain the raw fastq files for each sample.
samplesheet: "samplesheet.csv"

### File paths for input and output ###
# Files relative to PROJECT_ROOT
log_files: "code/metatranscriptomics-snakemake/workflow/logs"
reads_dir: "data/raw/metatranscriptomics_test/01_raw"
reads_trimmed: "data/raw/metatranscriptomics_test/02_trimmed"
reads_host_dep: "data/raw/metatranscriptomics_test/03_host_dep"
reads_rRNA_dep: "data/raw/metatranscriptomics_test/04_rRNA_dep"
assemblies_dir: "workspace/metatranscriptomics-snakemake/05_assemblies"
taxonomy_short_reads_dir: "workspace/metatranscriptomics-snakemake/06_kraken"
amr_screening_dir: "workspace/metatranscriptomics-snakemake/07_card_rgi"
rnaquast_dir: "workspace/metatranscriptomics-snakemake/08_rnaquast"
co-assembly_dir: "workspace/metatranscriptomics-snakemake/09_megahit_coassembly"
coassembly_index: "workspace/metatranscriptomics-snakemake/10_coassembly_index"
sorted_bam_dir: "workspace/metatranscriptomics-snakemake/11_sorted_assemblies"
prodigal_dir: "workspace/metatranscriptomics-snakemake/12_prodigal"
featurecounts_dir: "workspace/metatranscriptomics-snakemake/13_featurecounts"


### File paths for resources  ###
bowtie2_index: "code/metatranscriptomics-snakemake/resources/bowtie2_index/Cow_phiX"
sortmerna_DB: "/gpfs/fs7/aafc/projects/J-003165_abcc_rcba/code/metatranscriptomics-snakemake/resources/rRNA_DB/smr_v4.3_default_db.fasta"

### File paths for databases on common drives###
gtbd_DB: "/gpfs/fs7/aafc/common/reference/kraken2_gtdb/release220"
busco_lineages:
  bacteria: "/gpfs/fs7/aafc/common/reference/busco/busco_downloads/lineages/bacteria_odb12"
  archaea: "/gpfs/fs7/aafc/common/reference/busco/busco_downloads/lineages/archaea_odb12"

### File path for CARD database if the user set it up. This is a fallback if there is no common database
card_latest: "/gpfs/fs7/aafc/projects/J-003165_abcc_rcba/code/metatranscriptomics-snakemake/localDB"

### Parameters for rules ###
## preprocessing.smk
fastp:
  threads: 4
  cut_tail: true
  cut_front: true
  cut_mean_quality: 20
  cut_window_size: 4
  qualified_quality_phred: 15
  detect_adapter_for_pe: true
  length_required: 100
bowtie2_align:
  threads: 24
  bt2_threads: 12
  view_threads: 4
  sort_threads: 8
extract_unmapped_fastq:
  threads: 60
## sortmerna.smk
sortmerna_pe:
  threads: 48
## amr_short_reads.smk
rgi_bwt:
  threads: 20
## taxonomy.smk
kraken2:
  threads: 2
  conf_threshold: "0.5"
bracken:
  threads: 2
  readlen: 150
## sample_assembly.smk
rna_spades:
  threads: 48
  memory: "64000"
rnaquast_busco:
  threads: 4
